name: Bug Report
description: Report something not working with the project's code.
labels: [bug]
# See https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema
body:
  - type: markdown
    attributes:
      value: >
        Thank you for helping us by reporting a bug issue!
        Help us help you get things fixed.
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: What version of our software are you running?
      placeholder: "I don't know..."
      description: >
        It can really help if you let us know what version of our software you are using.
        Sometimes the fix to the bug has already been implemented and all that is needed is an update, but this will let us know for sure.
  - type: textarea
    id: environment
    attributes:
      label: Where were you running our software?
      description: >
        Operating system, browser, shell, anything to help us know what environment our software is (not) working within.
        Sometimes, this is vital.
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: >
        Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
