name: New Task
description: A request for something to be done that isn't really a bug fix or a new feature.
type: Task
labels: ["task"]
body:
  - type: markdown
    attributes:
      value: >
        We know not all things to do with a repository are clearly bug fixes or new features.
        Life isn't that simple.
        If you need to ask for anything else, this is for you.
  - type: textarea
    id: task
    attributes:
      label: What do you want us to do?
      description: >
        What is this task to be about?
        Please provide us with as much information as you think is relevant.
      placeholder: >
        I would like you to hop on one foot and let slip the doves of peace!
    validations:
      required: true
